### ISSUE TITLE
Move ACF definitions into separate file

### ISSUE THREAD

**Issue by mhueni** [power-coders/wp-powercoders-theme#12]
@memoibish can you please move the whole ACF definition part into a separate file (e.g. `./inc/acf-faq.php` and then load it from the `functions.php` (using `require_once(dirname(__FILE__) . '/inc/acf-faq.php');`)? Otherwise the `functions.php` will grow beyond readability...

Also, the `page_template` rule doesn't work on my side. I think it should read `'value' => 'faq.php',` in `functions.php:245`

https://github.com/power-coders/wp-powercoders-theme/blob/7e7be1121d5301ad2036ebdcca4732c8d8102a5c/functions.php#L134

**Comment by memoibish** [comment]
**page_template rule doesn't work on my side. I think it should read 'value' => 'faq.php', in functions.php:245**
For this it works on my side i changed it but i did not push it yesterday. 
and i will make a  separate file for ACF.

**Comment by mhueni** [comment]
sorry, I might have given you the wrong advice for using `require_once`. 
on my side the above code snippet works, but maybe this is different on Windows.
Maybe you have to use `get_template_directory()` (https://codex.wordpress.org/Function_Reference/get_template_directory)

```
require_once(get_template_directory() . '/inc/acf-faq.php');
```
